// layout.tsx (sin "use client")

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "./components/ClientProvider"; // Importar el componente del cliente

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ClientProvider>{children}</ClientProvider> {/* Usar el provider aquí */}
      </body>
    </html>
  );
}
